// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiU8uK0ZdsKP4rSnR6FP2LcYsVh43BvI8',
    appId: '1:77770027076:web:510b3841f89751de978c11',
    messagingSenderId: '77770027076',
    projectId: 'ride-share-23628',
    authDomain: 'ride-share-23628.firebaseapp.com',
    databaseURL: 'https://ride-share-23628-default-rtdb.firebaseio.com',
    storageBucket: 'ride-share-23628.appspot.com',
    measurementId: 'G-R9B2Q1BHH3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9ofKnDLSpvzrNKkEWVq-lqNcbeEVrxdk',
    appId: '1:77770027076:android:d40745d06d9ff2f0978c11',
    messagingSenderId: '77770027076',
    projectId: 'ride-share-23628',
    databaseURL: 'https://ride-share-23628-default-rtdb.firebaseio.com',
    storageBucket: 'ride-share-23628.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVJNoSy5TdUwwOB6d8gNeQyOSxnRYA9-w',
    appId: '1:77770027076:ios:f9f2ee7e1cddb0ca978c11',
    messagingSenderId: '77770027076',
    projectId: 'ride-share-23628',
    databaseURL: 'https://ride-share-23628-default-rtdb.firebaseio.com',
    storageBucket: 'ride-share-23628.appspot.com',
    iosBundleId: 'com.example.driverApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVJNoSy5TdUwwOB6d8gNeQyOSxnRYA9-w',
    appId: '1:77770027076:ios:f9f2ee7e1cddb0ca978c11',
    messagingSenderId: '77770027076',
    projectId: 'ride-share-23628',
    databaseURL: 'https://ride-share-23628-default-rtdb.firebaseio.com',
    storageBucket: 'ride-share-23628.appspot.com',
    iosBundleId: 'com.example.driverApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACmZ7tGEIZ9TM1gBtmMmkcMIrf9SoWPtQ',
    appId: '1:77770027076:web:d42e27d5ce19f4d8978c11',
    messagingSenderId: '77770027076',
    projectId: 'ride-share-23628',
    authDomain: 'ride-share-23628.firebaseapp.com',
    databaseURL: 'https://ride-share-23628-default-rtdb.firebaseio.com',
    storageBucket: 'ride-share-23628.appspot.com',
    measurementId: 'G-C1WV7CGVVS',
  );
}
